baseURL = "http://jmhammond.github.io"
languageCode = "en-us"
title = "Hammond's Notes"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[params]
hideFooter = true
defaultTheme = "auto"
disableSpecial1stPost = true
hidemeta = true

  [params.assets]
  theme_color = "#ffc217"

  [params.label]
  text = "Hammond's Notes"
  icon = "/wsu-logo.png"
  iconHeight = 48.0
  favicon = "/favicon.ico"
  favicon-32x32 = "/favicon-32x32.png"

  [params.profileMode]
  enabled = true

    [[params.profileMode.buttons]]
    name = "Blog Posts"
    url = "/blog"
    
    [[params.profileMode.buttons]]
    name = "Math Teaching Seminar"
    url = "/teaching_seminar"

    [[params.profileMode.buttons]]
    name = "Math 242: Calc 1"
    url = "/calc"

    [[params.profileMode.buttons]]
    name = "Math 321: Discrete 1"
    url = "http://www.wichita.edu/discretebook"
