baseURL = "http://jmhammond.github.io"
languageCode = "en-us"
title = "Hammond's Course Notes"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[params]
hideFooter = true
defaultTheme = "auto"
disableSpecial1stPost = true
hidemeta = true

  [params.assets]
  theme_color = "#ffc217"

  [params.label]
  text = "Course Notes"
  icon = "/wsu-logo.png"
  iconHeight = 48.0

  [params.profileMode]
  enabled = true
  subtitle = "Select your course below:"

    [[params.profileMode.buttons]]
    name = "Math 300: Evolution of Math"
    url = "/math300"

    [[params.profileMode.buttons]]
    name = "Math 123: Trig"
    url = "/trig"

    [[params.profileMode.buttons]]
    name = "Math 242: Calc 1"
    url = "/calc"

    [[params.profileMode.buttons]]
    name = "Math 321: Discrete 1"
    url = "http://www.wichita.edu/discretebook"

    [[params.profileMode.buttons]]
    name = "Math 531: History"
    url = "/history"
