#+title: Hammond's Blog And Class Posts
#+hugo_base_dir: ../
#+MACRO: more @@hugo:<!--more-->@@
#   to use this one, write {{{more}}}
#+MACRO: youtube @@hugo:{{< youtube id="$1" >}}@@
#  to use this, write {{{youtube(ID)}}}
#+hugo_paired_shortcodes: spoiler
#  to use this, write:
#     #+begin_spoiler
#      You need to click to see this, my friend.
#     #+end_spoiler

* Calculus 1 - Math 242
:PROPERTIES:
:EXPORT_HUGO_SECTION: calc
:END:

** Index page for calculus
:PROPERTIES:
:EXPORT_TITLE: Math 242: Calculus 1
:EXPORT_FILE_NAME: _index.html
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:
In which we learn about rates of change and areas, and applications to various contexts.

{{{more}}}

This content may or may not be updated.  I've copy-pasted some content from the Spring 2022 course, and I'm putting this together while I'm building the site.

... basically I need practice building the hugo blog.

... I'll update it eventually.

** Chapter 1
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: chapter1
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:
***  First test sample post :hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: First_test_file
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :mathjax true :ShowBreadCrumbs true
:END:

This is what you can do with calc
{{{more}}}
This is section 3.3  (and 3.4 below)

**** Increasing / Decreasing Test

- If $f'(x) > 0$ on an interval, then $f$ is increasing on that interval.
- If $f'(x) < 0$ on an interval, then $f$ is decreasing on that interval.
- If $f'(x) = 0$ on an interval, then $f$ is constant on that interval.


**** Youtube test:
There should be a video here
{{{youtube(J2h_bCkhmwM)}}}


**** Spoiler test:

#+begin_spoiler
You need to click to see this, my friend.
#+end_spoiler

* History - Math 300
:PROPERTIES:
:EXPORT_HUGO_SECTION: math300
:END:
** Index page
:PROPERTIES:
:EXPORT_TITLE: Math 300: Evolution of Mathematics
:EXPORT_FILE_NAME: _index.html
:END:

In which we learn that people are terribly interesting and math isn't terrible.

{{{more}}}

** Additional Resources
:PROPERTIES:
:EXPORT_FILE_NAME: AdditionalResources
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :mathjax true :ShowBreadCrumbs true
:END:
*** Incan empire and the Egyptian Rhind Papyrus
- and here's the [[http://www5.kb.dk/permalink/2006/poma/356/en/image/?open=idm45693536739296][1615 notes of Felipe Guaman on the Incan empire]]
- [[https://www.britishmuseum.org/collection/object/Y_EA10058][Here's a link to the Rhind Papyrus full image on the British Museum website.]]
*** Representing arithmetic and fractions
This is a link to [[https://archive.org/details/b29980343_0002/page/14/mode/2up][Florian Cajori's History of Mathematical Notations, volume 2]]. Specifically, it points to the history of the dollar sign, $, because that might be an interesting entry point into the book.

Simon Stevin's  /De Thiende/ ('The Tenth') in 1585
    - [[https://books.google.com/books?id=aVdIAQAAMAAJ&pg=PA9&ci=99%252C363%252C407%252C298&source=bookclip#v=onepage&q&f=false][You can find it here]] (a 1606 English edition)


** Daily Readings and Assignments
:PROPERTIES:
:EXPORT_FILE_NAME: DailyReadings
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :mathjax true :ShowBreadCrumbs true
:END:
*** This Week's Reading's and Assignments
Before class tomorrow (for each day of class!), please complete the following:
**** Day 2  (Wednesday, July 6)
- Read:
  - Sketch 1
  - Nutshell, pages 5-25
- Do:
  - Sketch 1 questions 1-3
  - The [[https://docs.google.com/document/d/1wVzn8FClW47TPj7Bei7jRBZWQqfugbGq9D8MxBD4wjc/edit?usp=sharing][Citation Activity linked]] here.

**** Day 3 (Thursday, July 7):
- Read:
  - Sketch 2
  - Sketch 4
- Do:
  - Sketch 2 questions 1, 4, 5
  - Sketch 4 questions 4, 6, 7
- Do you have modeling clay/playdoh? Can you dig a hole in your yard and get some wet dirt?
- Grab your 'clay,' a popsicle stick (or regular stick) and watch along to learn to write Cuineiform:
{{{youtube(zOwP0KUlnZg)}}}
**** Day 4 (Friday, July 8):
- Read:
  - Sketch 8
  - Sketch 12
- Do:
  - Sketch 8: Problems 2, 6
  - Sketch 12: problems 3, 4, 7
    - Note for problem 3, here's [[https://mathcs.clarku.edu/~djoyce/java/elements/bookVI/propVI31.html][Euclid's Elements Online]]
  - [[https://drive.google.com/open?id=1HQkCOwVp_W4tD87V-p5_OJWpqOcumyFKdGH2di-lqgk][Choice of Mathematicians for Biographies is Due (update the spreadsheet ]]and email by 9pm)
**** Day 5 (Monday, July 11):
- Try to find about 70 pennies (we want consistent-sized small circular discs) (it's okay if you can't, but if you have them, bring them!)
- Read:
  - Sketch 7
  - Sketch 9
- Do:
  - Sketch 7: Problems 1 and 2
  - Sketch 9: Problems 1, 2, 3
  - The first presentations are "due" tomorrow! Students are presenting Tuesday and Wednesday!
**** Day 6 (Tuesday, July 12): :noexport:
- Read:
  - Sketch 28
  - Sketch 10
- Do:
  - Sketch 28: Problems: (none assigned but take a look)
  - Sketch 10: Problems:  2 (try), 3, 5
- Read:

**** Day 7 (Wed, July 13) :noexport:
- Read:
  - Sketch 5
  - Sketch 11
- Do:
  - Sketch 5: Problems: 1, 3, 5
  - Sketch 11: Problems: 1, 3

**** Day 8 (Thur, July 14) :noexport:
- Read:
  - Sketch 17
  - Sketch 29
- Do:
  - Sketch 17: Problems 6, 7
  - Sketch 29: (none assigned)

**** Day 9 (Fri, July 15) :noexport:
- Read:
  - Sketch 14
  - Sketch 13
- Do:
  - Sketch 14: 1, 4
  - Sketch 13: 2, 4
  - First mathematician biography is Due Today, Friday ([[mailto:john.hammond@wichita.edu][Email to me]] by 9pm)
  - Be working on the Historical timeline overview for this mathematician

**** Day 10 (Mon, July 18) :noexport:
- Read:
  - Sketch 3
- Do:
  - Sketch 3: Problems 3, 4, 5
- History overview due today, Monday (Email by 9pm)
- The second presentations are "due" tomorrow! Students are presenting Tuesday and Wednesday!

**** Day 11 (Tue, July 19) :noexport:
- Read: Nutshell 22 - 66
- Do:
  - This section doesn't have homework questions, so this gives us a great opportunity!
    - Since we've now seen a "Large Nutshell" overview of math, let's take a moment to find the topic project that we (you) will be presenting. This is the [[https://docs.google.com/document/d/1NT5PZqf7E75kvPy1GXeAJBysQZ-Tx6jBioYrmwxxZXE/edit#bookmark=id.gbn7ed2zceub][MTA Project of the syllabus]].
      - What topic in math is really interesting to you?
      - What would you like to read more about?
      - Find the relevant sketch in MTA and look at the Projects section at the end.
      - Pick a project you'd like to cover and [[https://docs.google.com/spreadsheets/d/1_vNEo_lcZtNpSvIEpqwQoGFFHdc_HC8CzLUvCFDZM5M/edit?usp=sharing][claim it on this spreadsheet.]]
      - [[mailto:hammond@math.wichita.edu][Send me an email]] after you're done.

**** Day 12 (Wed, July 20) :noexport:
- Read:
  - Sketch 15
  - Sketch 16
- Do:
  - Sketch 15: question 1, 3, 4
  - Sketch 16: question 3 (use a ruler and plot points)

**** Day 13 (Thur, July 21) :noexport:
- Read:
  - Sketch 18
  - Sketch 27
- Do:
  - Sketch 18: 2, 4
  - Sketch 27: 1abc, 4

**** Day 14 (Fri, July 22) :noexport:
- Read:
  - Sketch 26
  - Sketch 30
- Do:
  - Sketch 26: 1, 3, 4
  - Sketch 30: 5  (531 students: all of them)


- Second mathematician biography is Due Today, Friday ([[mailto:john.hammond@wichita.edu][Email to me]] by 9pm)
- Be working on the Historical timeline overview for this mathematician

**** Day 16 (Mon, July 25) :noexport:
- Read:
  - Sketch 21
  - Sketch 22
- Do:
  - Sketch 21:
  - Sketch 22:

**** Day 17 (Tues, July 26) :noexport:
- Read:
  - Sketch 23
  - Sketch 24
- Do:
  - Sketch 23: Look through the questions and projects and do any that seem interesting. You might already be familiar with the material of all the questions.
  - Sketch 24: 1, 4, (5 if you feel adventurous)

**** Day 18 (Wed, July 27) :noexport:
- Read:
  - Sketch 19
  - Sketch 20
- Do:
  - Sketch 19: 4; If you have a globe explore 1, 2, and 3
  - Sketch 20: 1, 2;

Do you crochet? You can make a hyperbolic plane!

The pattern is incredibly simple: as long as you consistently increase the same for every row, you'll achieve a hyperbolic surface (constant negative curvature).

I've made several different increase counts. Let's do the simplest version:

1. Chain 20.
2. 4sc, inc.
3. repeat row 2 until it's as big as you want. The finished project will look like coral.


**** Day 19 (Thur, July 28) :noexport:
- Read:
  - Sketch 6
  - Sketch 26
- Do:
  - Sketch 6: 1, 2
  - Sketch 25: 3



**** Day 20 (Fri, July 29) Last day! :noexport:
**WE FINISHED MTA**
- We read the book cover to cover. Great job!

... actually... In lieu of a reading assignment, let me pose the following philosophical question - "What is math?"


*** Previous Readings and assignments
... nothing yet...

**** Week 1 :noexport:
**** Week 2 :noexport:

**** Week 3 :noexport:

**** Week 4 :noexport:

* Trig - Math 123
:PROPERTIES:
:EXPORT_HUGO_SECTION: trig
:END:

** Index page for trig
:PROPERTIES:
:EXPORT_TITLE: Math 123: Trigonometry
:EXPORT_FILE_NAME: _index.html
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:
In which we learn about triangles and circles and apply them in various contexts.

** Chapter 1
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: chapter1
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:
***  Another test sample post :hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: Trig_test
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :mathjax true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:

This is what you can do with trig
{{{more}}}
With words an whatnot.

* Blog Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
** Index page for blog posts
:PROPERTIES:
:EXPORT_TITLE: Blog posts
:EXPORT_FILE_NAME: _index.html
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowBreadCrumbs true
:END:
I ramble about grading, teaching, and/or tech.

{{{more}}}

... I'll update it eventually.

** Getting started with Hugo for course content. :hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: getting_started_with_hugo
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :mathjax true :ShowCodeCopyButtons true :ShowBreadCrumbs true
:END:
I wanted a "simple" way to write my class materials in Markdown. Hugo magically makes it a website.
{{{more}}}
I've been using Discourse for class content for about three years now - written in Markdown, I can easy mix text, math, and youtube videos and Discourse magically created the pre-class and post-class content pages. But of course that required students have a separate place to check for course materials, and I'm worried it wasn't viewed as often as I'd like.

Hugo takes Markdown and (almost) magically creates a static website. Nice!

In this post I'm going to document setting up the hugo blog for my course materials -- mostly for myself in case I need to recreate it in the future -- if you are reading this and are not me, let me know if it helps!

*** Basic setup of the hugo blog
... For this, look elsewhere and come back. (sorry)

Here's a [[https://github.com/jmhammond/math-courses][link to mine on GitHub]] with information about cloning and setting up.

*** Setting up Mathjax 3
There's really three things that need to happen to use Mathjax on a page:
1. You need to create a mathjax =partial=. This will live in ~site-name/layouts/partials/mathjax_support.html~:
      #+begin_src html
<script>
  MathJax = {
  tex: {
  packages: ['base', 'ams'],        // extensions to use
  inlineMath: [ ['$','$'], ['\\(','\\)'] ],
  displayMath: [             // start/end delimiter pairs for display math
  ['$$', '$$'],
  ['\\[', '\\]']
  ],
  processEscapes: true,      // use \$ to produce a literal dollar sign
  processEnvironments: true, // process \begin{xxx}...\end{xxx} outside math mode
  formatError:               // function called when TeX syntax errors occur
  (jax, err) => jax.formatError(err)
  }
  };
</script>
<script type="text/javascript" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
   #+end_src

2. and then in the ~site-name/layouts/extend_head.html~ file, add the following:
   #+begin_src
{{ if .Params.mathjax }}{{ partial "mathjax_support.html" . }}{{ end }}
    #+end_src
    The conditional means that mathjax won't load on every page (since it does add overhead). It will only be on pages that request it.

3. To add mathjax to the page, you need to add the page parameter to the (toml) frontmatter: ~mathjax= true~.


*** Fonts and Colors
In order to match some of the [[https://www.wichita.edu/services/strategic_communications/brand_standards/colors_and_fonts.php][look and feel of the official WSU website]], I specified css files for hugo which automatically get picked up and used. For this, I created a ~fonts.css~ and ~custom.css~ file in the folder ~site-name/assets/css/extended~.

*** Spoiler shortcode
If you want to be able to hide an answer/solution so students need to click to reveal it,

#+begin_spoiler
... like this ...
#+end_spoiler

I've created a simple spoiler tag as a [[https://gohugo.io/content-management/shortcodes/][Hugo shortcode.]]  The above example was created by:

#+begin_src html
{{ < spoiler > }}
... like this ...
{{ </ spoiler > }}
#+end_src

Add this file to ~site-name/layouts/shortcodes/spoiler.html~
#+begin_src html
<div class="spoiler"><details {{ if (eq (.Get "openByDefault") true) }} open=true {{ end }}>
  <summary markdown="span">Click to reveal the answer.</summary>
  {{ .Inner | markdownify }}
</details></div>
#+end_src

and add this CSS to the ~site-name/assets/css/extended/custom.css~ file:
#+begin_src css
/* For the spoiler tags  */

.spoiler {
    margin: 0 5px 40px 5px;
    border: 1px solid var(--border);
    background: var(--entry);
    border-radius: var(--radius);
    padding: 0.4em;
}

.dark .spoiler {
    background: var(--entry);
}

.spoiler details summary {
    cursor: zoom-in;
    margin-inline-start: 20px;
}

.spoiler details[open] summary {
    cursor: zoom-out;
}

.spoiler .details {
    display: inline;
    font-weight: 500;
}

.spoiler .inner {
    margin: 0 20px;
    padding: 10px 20px;
}

.spoiler li ul {
    margin-inline-start: var(--gap);
}

.spoiler summary:focus {
    outline: 0;
}
#+end_src
